/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class ImagePaths {
  static const String aboutUs = "assets/images/ic_aboutus.svg";
  static const String backArrow = "assets/images/ic_back_arrow.svg";
  static const String add = "assets/images/ic_add.svg";
  static const String airConditioning = "assets/images/ic_air_conditioning.svg";
   static const String animalsCare = "assets/images/ic_animalscare.svg";
  static const String approve = "assets/images/ic_approve.svg";
  static const String arrowDown = "assets/images/ic_arrowdown.svg";
  static const String arrowLeft = "assets/images/ic_arrowleft.svg";
  static const String avatar = "assets/images/ic_avatar.svg";
  static const String avatarImage = "assets/images/ic_avatar_image.png";
  static const String barcode = "assets/images/ic_barcode.svg";
  static const String bell = "assets/images/ic_bell.svg";
  static const String calender = "assets/images/ic_calender.svg";
  static const String camera = "assets/images/ic_camera.svg";
  static const String cameraTwo = "assets/images/ic_camera_2.svg";
  static const String cameras = "assets/images/ic_cameras.svg";
  static const String carParking = "assets/images/ic_carparking.svg";
  static const String carPentry = "assets/images/ic_carpentry.svg";
  static const String carPetClean = "assets/images/ic_carpetclean.svg";
  static const String carWashing = "assets/images/ic_carwashing.svg";
  static const String changePassword = "assets/images/ic_changepassword.svg";
  static const String close = "assets/images/ic_close.svg";
  static const String compoundRules = "assets/images/ic_compoundrules.svg";
  static const String curtains = "assets/images/ic_curtains.svg";
  static const String deapClean = "assets/images/ic_deapclean.svg";
  static const String disable = "assets/images/ic_disable.svg";
  static const String edit = "assets/images/ic_edit.svg";
  static const String electricity = "assets/images/ic_electricity.svg";
  static const String expiredDate = "assets/images/ic_expired_date.svg";
  static const String facebook = "assets/images/ic_facebook.svg";
  static const String facebookWithOutBorder = "assets/images/ic_facebook_2.svg";
  static const String faq = "assets/images/ic_faq.svg";
  static const String floors = "assets/images/ic_floors.svg";
  static const String coloredGallery = "assets/images/ic_gallary.svg";
  static const String gallery = "assets/images/ic_gallery.svg";
  static const String gym = "assets/images/ic_Gym.svg";
  static const String handelGates = "assets/images/ic_handel_gates.svg";
  static const String headPassword = "assets/images/ic_head_password.svg";
  static const String selectedHome = "assets/images/ic_home.svg";
  static const String unselectedHome = "assets/images/ic_home_2.svg";
  static const String homeClean = "assets/images/ic_homeclean.svg";
  static const String hourlyClean = "assets/images/ic_hourlyclean.svg";
  static const String instagram = "assets/images/ic_instagram.svg";
  static const String instagramTwo = "assets/images/ic_instagram_2.svg";
  static const String keys = "assets/images/ic_keys.svg";
  static const String landscape = "assets/images/ic_landscape.svg";
  static const String language = "assets/images/ic_language.svg";
  static const String languageTwo = "assets/images/ic_language_2.svg";
  static const String linkedin = "assets/images/ic_linkedin.svg";
  static const String loading = "assets/images/ic_loading.svg";
  static const String locations = "assets/images/ic_locations.svg";
  static const String unSelectedMaintenance =
      "assets/images/ic_maintenance.svg";
  static const String selectedMaintenance =
      "assets/images/ic_maintenance_2.svg";
  static const String manageMaintenance =
      "assets/images/ic_manage_maintenance.svg";
  static const String microphone = "assets/images/ic_microphone.svg";
  static const String minus = "assets/images/ic_minus.svg";
  static const String mobile = "assets/images/ic_mobile.svg";
  static const String monthlyCleaning = "assets/images/ic_monthlycleaning.svg";
  static const String unSelectedMore = "assets/images/ic_more.svg";
  static const String selectedMore = "assets/images/ic_more_2.svg";
  static const String notificationWithAction = "assets/images/ic_noti.svg";
  static const String notification = "assets/images/ic_notification.svg";
  static const String onlinePayment = "assets/images/ic_online_payment.svg";
  static const String persons = "assets/images/ic_persons.svg";
  static const String plumbing = "assets/images/ic_plumbing.svg";
  static const String profile = "assets/images/ic_profile.svg";
  static const String receiver = "assets/images/ic_reciver.svg";
  static const String complain = "assets/images/ic_reportissues.svg";
  static const String rules = "assets/images/ic_rules.svg";
  static const String scancode = "assets/images/ic_scancode.svg";
  static const String search = "assets/images/ic_Search.svg";
  static const String unSelectedServices = "assets/images/ic_services.svg";
  static const String selectedServices = "assets/images/ic_services_2.svg";
  static const String settings = "assets/images/ic_settings.svg";
  static const String share = "assets/images/ic_share.svg";
  static const String shareBlack = "assets/images/ic_share_black.svg";
  static const String showPassword = "assets/images/ic_show_password.svg";
  static const String shutter = "assets/images/ic_shutter.svg";
  static const String socialMedia = "assets/images/ic_social_media.svg";
  static const String sort = "assets/images/ic_sort.svg";
  static const String stuff = "assets/images/ic_stuff.svg";
  static const String termsAndConditions =
      "assets/images/ic_termsandconditions.svg";
  static const String timeWork = "assets/images/ic_timework.svg";
  static const String timeWork1 = "assets/images/ic_timework_1.svg";
  static const String toggle = "assets/images/ic_toggle.svg";
  static const String twitter = "assets/images/ic_twitter.svg";
  static const String users = "assets/images/ic_users.svg";
  static const String version = "assets/images/ic_version.svg";
  static const String video = "assets/images/ic_video.svg";
  static const String visitors = "assets/images/ic_visitors.svg";
  static const String volume = "assets/images/ic_volume.svg";
  static const String volumeOff = "assets/images/ic_volumeoff.svg";
  static const String unselectedWall = "assets/images/ic_wall.svg";
  static const String selectedWall = "assets/images/ic_wall_2.svg";
  static const String whatsapp = "assets/images/ic_landing_whatsapp.svg";
  static const String youtube = "assets/images/ic_youtube.svg";
  static const String uploadMediaGallery =
      "assets/images/ic_upload_media_gallery.svg";
  static const String grayCalendar = "assets/images/ic_gray_calender.svg";
  static const String frame = "assets/images/ic_frame.svg";
  static const String messageNotifications =
      "assets/images/ic_message_notification_1.svg";
  static const String edit2 = "assets/images/ic_edit2.svg";
  static const String buildings = "assets/images/ic_buildings.svg";
  static const String qr = "assets/images/ic_qr.svg";
  static const String profileGroup = "assets/images/ic_profile_group.svg";

  static const String calendarEvents = "assets/images/ic_calandar_events.svg";
  static const String profilePlaceHolder =
      "assets/images/ic_profile_place_holder.png";
  static const String communityRequest =
      "assets/images/ic_community_request.svg";
  static const String stuffImage = "assets/images/ic_stuff.png";
  static const String galleryMore = "assets/images/ic_gallery_more.svg";
  static const String globe = "assets/images/ic_globe.svg";
  static const String handHoldingPhone =
      "assets/images/ic_hand_holding_phone.png";
  static const String one = "assets/images/ic_test_one.png";
  static const String two = "assets/images/ic_test_two.png";
  static const String three = "assets/images/ic_test_three.png";
  static const String four = "assets/images/ic_test_four.png";
  static const String flagPlaceHolder = "assets/images/ic_flag_placeholder.jpg";
  static const String fabClose = "assets/images/ic_fab_close.svg";

  static const String emptyGallery = "assets/images/ic_gallery_empty.svg";
  static const String deactivated = "assets/images/ic_deactivated.svg";
  static const String noInternet = "assets/images/ic_no_internet.svg";
  static const String play = "assets/images/ic_play.svg";
  static const String pause = "assets/images/ic_pause.svg";
  static const String playAudio = "assets/images/ic_audio_play.svg";
  static const String pauseAudio = "assets/images/ic_audio_pause.svg";
  static const String stopRecord = "assets/images/ic_stop.svg";
  static const String star = "assets/images/ic_star.svg";
  static const String selectDate = "assets/images/ic_select_date.svg";
  static const String uploadImagePlaceholder =
      "assets/images/ic_image_placeholder.svg";
  static const String arrowRight = "assets/images/ic_arrowright.svg";
  static const String documentUpload = "assets/images/ic_document_upload.svg";
  static const String pdf = "assets/images/ic_pdf.svg";
  static const String downloadFile = "assets/images/ic_download_file.svg";
  static const String circleAdd = "assets/images/ic_circe_add.svg";
  static const String compoundEmpty = "assets/images/ic_no_compound.svg";
  static const String noServices = "assets/images/ic_no_services.svg";
  static const String noSupport = "assets/images/ic_no_support.svg";
  static const String scanBarcodeIcon = "assets/images/ic_scanbarcode.svg";
  static const String payment = "assets/images/ic_pay_now.svg";
  static const String visa = "assets/images/ic_visa.svg";
  static const String dollars = "assets/images/ic_dollars.svg";
  static const String noMoney = "assets/images/ic_no_money.svg";
  static const String iconSignature = "assets/images/ic_signature.svg";
  static const String noFamily = "assets/images/ic_no_family_member.svg";
  static const String noCars = "assets/images/ic_no_car.svg";
  static const String delete = "assets/images/ic_delete.svg";
  static const String car = "assets/images/ic_car.svg";
  static const String imagePlaceHolder =
      "assets/images/ic_image_place_holder.png";
  static const String addCircle = "assets/images/ic_add_circle.svg";
  static const String deActive = "assets/images/ic_deactive.svg";
  static const String arrowStatus = "assets/images/ic_arrow_status.svg";
  static const String personalCard = "assets/images/ic_personal_card.svg";
  static const String historyEmptyScreen = "assets/images/ic_no_qr_code.svg";
  static const String delegate = "assets/images/ic_delegate.svg";
  static const String switchCompound = "assets/images/ic_switch_compound.svg";
  static const String deleteAccount = "assets/images/ic_delete_account.svg";
  static const String qrImageIcon = "assets/images/ic_qr_image.svg";
  static const String comment = "assets/images/ic_comment.svg";
  static const String payNow = "assets/images/ic_pay_now.svg";
  static const String approved = "assets/images/ic_approved.svg";
  static const String emptyOrders = "assets/images/ic_empty_orders.svg";
  static const String sendMessage = "assets/images/ic_send_message.svg";
  static const String commentsEmpty = "assets/images/ic_comments_empty.svg";
  static const String noMessages = "assets/images/ic_no_message.svg";
  static const String rating = "assets/images/ic_rating.svg";
  static const String rateStar = "assets/images/ic_rate_star.svg";
  static const String starSelected = "assets/images/ic_star_1.svg";
  static const String completeStatus = "assets/images/complete_status.svg";
  static const String emptyEvents = "assets/images/ic_no_event.svg";
  static const String emptyEventsHome = "assets/images/ic_no_event.svg";
  static const String emptySurveysHome = "assets/images/ic_no_survey.svg";
  static const String emptyNotification =
      "assets/images/ic_notification_empty.svg";
  static const String surveyCount = "assets/images/ic_survey_count.svg";
  static const String wallEmpty = "assets/images/ic_wall_empty.svg";
  static const String noItems = "assets/images/ic_no_items.svg";
  static const String noImages = "assets/images/ic_no_image.svg";
  static const String emptySubscription =
      "assets/images/ic_empty_subscription.svg";
  static const String delegationEmptyIcon =
      "assets/images/ic_delegation_empty.svg";
  static const String noInternetConnection = "assets/images/ic_no_internet.png";
  static const String stepCar = "assets/images/ic_step_car.svg";
  static const String stepInfo = "assets/images/ic_step_info.svg";
  static const String stepFamily = "assets/images/ic_step_family.svg";
  static const String stepUnit = "assets/images/ic_step_unit.svg";
  static const String stepFiles = "assets/images/ic_step_files.svg";
  static const String resetPasswordSvg = "assets/images/ic_reset_password.svg";
  static const String resetPassword = "assets/images/ic_reset_password.png";
  static const String passwordLock = "assets/images/ic_password_lock.svg";
  static const String switchSplash = "assets/images/ic_switch_splash.svg";
  static const String scanQR = "assets/images/ic_scan_qr.svg";
  static const String scanQRDelegation =
      "assets/images/ic_scan_qr_delegation.svg";

  static const String success = "assets/images/ic_success.svg";
  static const String error = "assets/images/ic_cancel.svg";
  static const String warning = "assets/images/ic_warning.svg";
  static const String info = "assets/images/ic_information.svg";

  static const String cancelRate = "assets/images/ic_cancel_rate.svg";
  static const String lock = "assets/images/ic_lock.svg";
  static const String unitBadge = "assets/images/ic_unit_badge.svg";
  static const String userBadge = "assets/images/ic_user_badge.svg";
  static const String emptyUnit = "assets/images/ic_empty_unit.svg";
  static const String itemUserBadge = "assets/images/ic_item_user_badge.svg";

  static const String refresh = "assets/images/ic_refresh.svg";

  static const String noServicesHome = "assets/images/ic_no_services.svg";
  static const String noSupportHome = "assets/images/ic_no_support.svg";
  static const String ratingStarYellow =
      "assets/images/ic_star_rating_yellow.svg";
  static const String ratingStarGrey = "assets/images/ic_star_rating_grey.svg";
  static const String discountIcon = "assets/images/ic_discount.svg";
  static const String icTimer = "assets/images/IC_timer.svg";
  static const String icUpdate = "assets/images/ic_update.svg";
  static const String icStuffEmpty = "assets/images/ic_stuff_empty.svg";
  static const String icBookingEmpty = "assets/images/ic_booking_empty.svg";
  static const String icMaintenanceEmpty =
      "assets/images/ic_maintenance_empty.svg";
  static const String icIconContactForm =
      "assets/images/ic_icon-contact-form.svg";
  static const String icCall = "assets/images/ic_call.svg";
  static const String call = "assets/images/ic_landing_all.svg";
  static const String maximize = "assets/images/ic_m_square.svg";
  static const String whatsApp = "assets/images/ic_landing_whatsapp.svg";
  static const String icWebArea = "assets/images/ic_web_area.svg";

  static const String icWebMobiles = "assets/images/ic_web_mobiles.png";
  static const String icWebGoogleStore = "assets/images/ic_web_google_play.png";
  static const String icWebAppStore = "assets/images/ic_web_app_store.png";
  static const String icWebGalleryStore = "assets/images/ic_web_gallery.png";
  static const String icArrowUp = "assets/images/ic_arrow_up.svg";
  static const String icWebInterestCityEye =
      "assets/images/ic_web_interest_cityeye.svg";
  static const String icWebCall = "assets/images/ic_web_call.svg";
  static const String icWebCall1 = "assets/images/ic_web_call_1.svg";
  static const String icWebSettings = "assets/images/ic_web_settings.svg";
  static const String icWebReserve = "assets/images/ic_web_reserve.svg";
  static const String icWebVoting = "assets/images/ic_web_voting.svg";
  static const String icWebPayments = "assets/images/ic_web_payments.svg";
  static const String icWebArrowLeft = "assets/images/ic_web_arrow_left.svg";
  static const String icWebArrowRight = "assets/images/ic_web_arrow_right.svg";
  static const String qrCodePayment = "assets/images/qr-code-payment.svg";
  static const String bg = "assets/images/BG.svg";
  static const String webLocation = "assets/images/ic_location.svg";
  static const String electric = "assets/images/ic_electric_num.svg";
  static const String area = "assets/images/ic_area.svg";
  static const String bank = "assets/images/ic_bank.svg";
  static const String bedRoom = "assets/images/ic_bed_room.svg";
  static const String brush = "assets/images/ic_brush.svg";
  static const String garden = "assets/images/ic_garden.svg";
  static const String gasNumber = "assets/images/ic_gas_num.svg";
  static const String hospital = "assets/images/ic_hospital.svg";
  static const String parking = "assets/images/ic_parking.svg";
  static const String school = "assets/images/ic_school.svg";
  static const String webCalender = "assets/images/ic_web_calendar.svg";
  static const String hall = "assets/images/ic_hall.svg";
  static const String stars = "assets/images/ic_star.svg";
  static const String likes = "assets/images/ic_like.svg";
  static const String units = "assets/images/ic_units.svg";
  static const String projects = "assets/images/ic_projects.svg";
  static const String icFacilitation = "assets/images/ic_facilitation.svg";
  static const String clock = "assets/images/clock.svg";
  static const String icTimePlan = "assets/images/ic_time_plan.svg";
  static const String icUnit = "assets/images/ic_unit.svg";
  static const String icInstallment = "assets/images/ic_installment.svg";
  static const String icViolations = "assets/images/ic_Violations.svg";
  static const String icResidentService =
      "assets/images/ic_resident_services.svg";
  static const String icTimeline = "assets/images/ic_timeline.svg";

  static const String fady = "assets/images/fady.png";

  static const String logoBg = "assets/images/logo.png";
  static const String fadyLogo1 = "assets/images/fady_logo.png";
  static const String fadyLogo2 = "assets/images/fady_logo1.png";
  static const String logo1 = "assets/images/1.png";
  static const String logo2 = "assets/images/2.png";
  static const String logo3 = "assets/images/3.png";
  static const String light = "assets/images/gif/icons/light.png";
  static const String dark = "assets/images/gif/icons/dark.png";
  static const String android = "assets/images/gif/icons/android.svg";
  static const String apple = "assets/images/gif/icons/apple.svg";
  static const String web = "assets/images/gif/icons/website.svg";
  static const String newLogo1 = "assets/images/new_logo1.png";
  static const String newLogo2 = "assets/images/new_logo2.png";
  static const String newLogo3 = "assets/images/new_logo3.png";
  static const String hi = "assets/images/gif/hi.gif";

  static const String concept = "assets/images/gif/icons/concept.svg";
  static const String database = "assets/images/gif/icons/database.svg";
  static const String design = "assets/images/gif/icons/design.svg";
  static const String dev = "assets/images/gif/icons/dev.svg";
  static const String extra = "assets/images/gif/icons/extra.svg";
  static const String map = "assets/images/gif/icons/map.svg";
  static const String flutter = "assets/images/gif/icons/mobile&web.svg";
  static const String state = "assets/images/gif/icons/state.svg";
  static const String storage = "assets/images/gif/icons/storage.svg";
  static const String test = "assets/images/gif/icons/test.svg";
  static const String website = "assets/images/gif/icons/website.svg";
  static const String skills = "assets/images/gif/icons/skill.png";
  static const String project = "assets/images/gif/icons/project.png";
  static const String experience = "assets/images/gif/icons/experience.png";
  static const String contact = "assets/images/gif/icons/contact.png";
  static const String api = "assets/images/gif/icons/api.png";
  static const String clean = "assets/images/gif/icons/clean.png";
  static const String conti = "assets/images/gif/icons/conti.png";
  static const String dataRecovery =
      "assets/images/gif/icons/data-recovery.png";
  static const String performance = "assets/images/gif/icons/performance.png";
  static const String responsive = "assets/images/gif/icons/responsive.png";
  static const String versionControl =
      "assets/images/gif/icons/version_control.png";
  static const String webDev = "assets/images/gif/icons/web.png";
  static const String notifications =
      "assets/images/gif/icons/notification.png";

  static const String bmi = "assets/images/gif/lottie/1.jpg";
  static const String learn = "assets/images/gif/lottie/2.jpg";
  static const String youtuber = "assets/images/gif/lottie/3.jpg";
  static const String popular = "assets/images/gif/lottie/4.jpg";
  static const String orders = "assets/images/gif/lottie/5.jpg";
  static const String ecommerce = "assets/images/gif/lottie/6.jpg";
  static const String newspaper = "assets/images/gif/lottie/7.jpg";
  static const String quiz = "assets/images/gif/lottie/8.jpg";
  static const String faceBook = "assets/images/gif/lottie/9.jpg";
  static const String note = "assets/images/gif/lottie/10.jpg";
  static const String shop = "assets/images/gif/lottie/11.jpg";
  static const String ava = "assets/images/gif/lottie/13.jpg";
  static const String weather = "assets/images/gif/lottie/1.jpg";
  static const String news = "assets/images/gif/lottie/88.jpg";
  static const String androidNote = "assets/images/gif/lottie/15.jpg";
  static const String androidWhatsApp = "assets/images/gif/lottie/16.jpg";
  static const String drawing = "assets/images/gif/lottie/17.jpg";
}
